baseURL       = "https://oswaldchartrainnws.netlify.app"
languageCode  = "fr-FR"
title         = "Roxo | NWS portfolio starter theme"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "À propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  # Stylesheet
  css = ["css/custom.css", "css/test.css"]

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re a Design Studio That Belies In the Great Ideas"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      phone   = "06.51.19.57.91"
      email   = "ochartrai@normandiewebschool.fr"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan de site"
        [[params.footer.sitemap.link]]
          name = "À propos de moi"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Mes projets"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "réseaux sociaux"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "https://www.behance.net/oswaldchartrain"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "https://dribbble.com/yugishan"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/oswaaalld/"
      # Footer Service
      [params.footer.service]
        title       = "J'aide les marques à:"
        description = "Développer des design<br>créé leur site internet<br>créé leur identité visuelle"
